# Generated by Django 4.2.17 on 2026-07-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('elderly', 'Elderly Person'), ('mobility', 'Person with Mobility Impairment'), ('hearing', 'Person with Hearing Impairment'), ('caregiver', 'Caregiver'), ('volunteer', 'Volunteer')], max_length=20),
        ),
    ]
