# Generated by Django 4.2.17 on 2026-07-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Elderly Person', 'Elderly Person'), ('Person with Mobility Impairment', 'Person with Mobility Impairment'), ('Person with Hearing Impairment', 'Person with Hearing Impairment'), ('Care Representative', 'Care Representative'), ('Caregiver', 'Caregiver'), ('Volunteer', 'Volunteer')], max_length=50),
        ),
    ]
