# Generated by Django 4.2.17 on 2026-08-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_servicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carerepresentativeconnection',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='carerepresentativeconnection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='carerepresentativerequest',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='carerepresentativerequest',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='volunteerassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='volunteerassignment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteerassignment',
            name='volunteer',
        ),
        migrations.AlterField(
            model_name='directcaregiverbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='directvolunteerbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='CaregiverAssignment',
        ),
        migrations.DeleteModel(
            name='CareRepresentativeConnection',
        ),
        migrations.DeleteModel(
            name='CareRepresentativeRequest',
        ),
        migrations.DeleteModel(
            name='VolunteerAssignment',
        ),
    ]
