# Generated by Django 4.2.30 on 2026-08-10 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_remove_carerepresentativeconnection_representative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('reminder_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Taken', 'Taken'), ('Missed', 'Missed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
