# Generated by Django 4.2.17 on 2026-08-12 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_medicinereminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencySOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Activated', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_sos_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
