# Generated by Django 4.2.30 on 2026-08-12 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_feedback_caregiver_feedback_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='caregiver',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='feedback',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
