# Generated by Django 4.2.17 on 2026-08-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Booking', 'Booking'), ('Service', 'Service'), ('Medicine', 'Medicine'), ('SOS', 'SOS'), ('Feedback', 'Feedback')], max_length=20),
        ),
    ]
