# Generated by Django 4.2.17 on 2026-08-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='directcaregiverbooking',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='directcaregiverbooking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directcaregiverbooking',
            name='booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directcaregiverbooking',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='directcaregiverbooking',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='directcaregiverbooking',
            name='service',
            field=models.CharField(blank=True, choices=[('Home Support', 'Home Support'), ('Hospital Assistance', 'Hospital Assistance')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='directvolunteerbooking',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='directvolunteerbooking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directvolunteerbooking',
            name='booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directvolunteerbooking',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='directvolunteerbooking',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='directvolunteerbooking',
            name='service',
            field=models.CharField(blank=True, choices=[('Shopping Assistance', 'Shopping Assistance'), ('Bank Assistance', 'Bank Assistance'), ('Transport Assistance', 'Transport Assistance'), ('Hospital Accompaniment', 'Hospital Accompaniment'), ('General Support', 'General Support')], default='', max_length=50),
        ),
    ]
