# Generated by Django 4.2.17 on 2026-08-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_directcaregiverbooking_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directcaregiverbooking',
            name='service',
            field=models.CharField(blank=True, choices=[('Home Support', 'Home Support'), ('Hospital Assistance', 'Hospital Assistance'), ('Medication Support', 'Medication Support'), ('Health & Wellness Support', 'Health & Wellness Support'), ('Post-Hospital Care', 'Post-Hospital Care')], default='', max_length=50),
        ),
    ]
