# Generated by Django 4.2.17 on 2026-08-18 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0019_alter_directcaregiverbooking_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Booking', 'Booking'), ('Service', 'Service'), ('Medicine', 'Medicine'), ('SOS', 'SOS'), ('Feedback', 'Feedback'), ('System', 'System')], max_length=20),
        ),
        migrations.CreateModel(
            name='RepresentedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('person_type', models.CharField(choices=[('Elderly Person', 'Elderly Person'), ('Person with Mobility Impairment', 'Person with Mobility Impairment'), ('Person with Hearing Impairment', 'Person with Hearing Impairment')], max_length=50)),
                ('relationship', models.CharField(choices=[('Parent', 'Parent'), ('Child', 'Child'), ('Spouse', 'Spouse'), ('Sibling', 'Sibling'), ('Relative', 'Relative'), ('Guardian', 'Guardian'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('medical_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_representative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='represented_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
