# Generated by Django 4.2.30 on 2026-08-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencysos',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emergency_contact_phone',
        ),
        migrations.AddField(
            model_name='emergencysos',
            name='emergency_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
