# Generated by Django 4.2.30 on 2026-08-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_emergencysos_emergency_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencysos',
            name='emergency_message',
            field=models.TextField(blank=True),
        ),
    ]
