# Generated by Django 4.2.30 on 2026-08-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_emergencysos_emergency_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam')], default='en', max_length=10),
        ),
    ]
