# Generated by Django 4.2.17 on 2026-08-19 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0024_alter_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='directcaregiverbooking',
            name='care_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_representative_caregiver_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directcaregiverbooking',
            name='is_care_representative_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directcaregiverbooking',
            name='represented_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_service_bookings', to='users.representedperson'),
        ),
        migrations.AddField(
            model_name='directvolunteerbooking',
            name='care_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_representative_volunteer_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directvolunteerbooking',
            name='is_care_representative_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directvolunteerbooking',
            name='represented_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_service_bookings', to='users.representedperson'),
        ),
    ]
