# Generated by Django 4.2.30 on 2026-10-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_userprofile_verification_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directcaregiverbooking',
            name='duration',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='directvolunteerbooking',
            name='duration',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
